accounts:
  - name: alice
    coins: ['20000token', '200000000stake']
  - name: bob
    coins: ['10000token', '100000000stake']
  - name: admin
    coins: ['10000token', '100000000stake']
    mnemonic: nation aim predict ticket friend fetch under undo dirt rapid explain text cloud empower slot year blanket vacant job load lock account devote core
validator:
  name: alice
  staked: '100000000stake'
